# Generated by Django 4.2.11 on 2024-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=255),
        ),
    ]
